# Generated by Django 4.0.1 on 2022-02-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_opened", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ("id",)},
        ),
    ]
