# Generated by Django 4.0.1 on 2023-03-15 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_code_discount_discount_discount_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.tour'),
        ),
    ]
