# Generated by Django 4.0.1 on 2023-03-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0002_tour_attractions_tour_children_ok_tour_end_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('jp', 'Японский')], default='ru', max_length=2),
        ),
    ]
