# Generated by Django 4.0.1 on 2022-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('starts_at', models.DateTimeField(null=True)),
                ('ends_at', models.DateTimeField(null=True)),
                ('points', models.ManyToManyField(to='along_neva_channels.Point')),
            ],
        ),
    ]
